name: test
on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.9'
    - run: pip install -U pip
    - run: pip install poetry
    - run: poetry install
    - run: poetry run pytest tests --cov
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        debug: true
        coverageCommand: poetry run coverage lcov
        coverageLocations: coverage.lcov:lcov